### PR TITLE
Docker env update

### PR DESCRIPTION
**Pull request by birkof**
- using mysql 5 latest version
- single compose file
- install dependencies through web container

### CODE REVIEW

**Comment by simpliste** [comment]
I also ran into the mysql problem. The version of Laravel that is used in akounting does not support the latest version of mysql(8).

See: https://github.com/laravel/framework/pull/23948

**Comment by birkof** [comment]
@simpliste thats why in this configuration I am using mysql:5

**Comment by denisdulici** [comment]
Thanks guys. @carvallegro @beinbm any comment?

**Comment by beinbm** [comment]
i really like the changes! thank you @birkof

**Comment by denisdulici** [comment]
Thanks Daniel

**Comment by birkof** [comment]
Glad I could help 🎉

**Pull request merged**
