### PR TITLE
Add Enlightn to the workflow

### PR DESCRIPTION
**Pull request by paras-malhotra**

### CODE REVIEW

**Comment by paras-malhotra** [comment]
@denisdulici not sure what's happening here. It's working for https://github.com/paras-malhotra/akaunting/pull/1 and notice the `***` in the check on my repo v/s the blanks in this repo.

GH_action

**Comment by paras-malhotra** [comment]
@denisdulici the secrets are missing in this repo. You'll need to create them as described [here](https://docs.github.com/en/actions/reference/encrypted-secrets#creating-encrypted-secrets-for-a-repository).

I added a Github step to confirm this.

Here's how it shows for this repo:
akaunting_secret

Here's how it should show (shows on my fork):
paras_secret

**Comment by denisdulici** [comment]
They're available at organization level and work's fine for [Crowdin action](https://github.com/akaunting/akaunting/blob/master/.github/workflows/translations.yml#L36) 🤔 

Screenshot_750

**Comment by paras-malhotra** [comment]
Wierd, can you try adding the secrets at the repo level?

**Comment by denisdulici** [comment]
I did that and re-run the action but the same 😞 

Screenshot_751

**Comment by paras-malhotra** [comment]
That's so wierd. Can you try deleting and re-running one last time? If that doesn't work, we can close this PR and I'll get in touch with the Github folks. Sorry for taking up so much of your time. ☹️

**Comment by denisdulici** [comment]
The same:

Screenshot_752

**Comment by paras-malhotra** [comment]
@denisdulici sorry for taking up so much of your time. Let's close this PR and I'll come back if I get a good response from Github.

**Comment by paras-malhotra** [comment]
Hi @denisdulici, I've discovered the issue.

> In order to protect public repositories for malicious users we run all pull request workflows raised from repository forks with a read-only token and no access to secrets.

Source: https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/

Is it possible for you to merge this PR with the failing Enlightn workflow and possibly test the workflow on subsequent PRs? I think it should work that way.

**Comment by denisdulici** [comment]
Any reason to comment the `TrustProxies` middleware?

**Comment by paras-malhotra** [comment]
@denisdulici, that seems to be an oversight for the [Unused Global Middleware check](https://www.laravel-enlightn.com/docs/performance/unused-global-middleware-analyzer.html). Just saw that your [docs](https://akaunting.com/docs/developer-manual/reverse-proxy) refer to setting up reverse proxies. Have fixed that now.

**Pull request merged**
