### PR TITLE
Fix issue in translation `ar-SA`

### PR DESCRIPTION
**Pull request by michaelnabil230**
- Fix the translation and `HTML` tag

### CODE REVIEW

**Comment by denisdulici** [comment]
You can use Crowdin for translations https://crowdin.com/project/akaunting

**Comment by michaelnabil230** [comment]
Hi @denisdulici 
This is a problem in the translation, it is not a simple thing missing in the translation, it will disable something else in the html tags when the render in browser and also there will be a problem with the directions when you add the rtl style

**Comment by michaelnabil230** [comment]
Also, if you open the code, you will see that there is a wrongly closed html tag

**Comment by michaelnabil230** [comment]
@denisdulici 
Please pay attention

**Pull request closed without merging**
