### PR TITLE
fixes recurring issues with date & timezone

### PR DESCRIPTION
**Pull request by themazim**
fixes unintended recurring bill & invoice create due to modified today date & 
fixes wrong timezone due to missing company settings

### CODE REVIEW

**Comment by themazim** [comment]
fixes recurring not working if timezone differs to companies timezone too.

**Comment by Gwemox** [comment]
Please merge this bug fix ! Without this PR, recurring doesn't work...

**Comment by themazim** [comment]
Akaunting seems to be dead.

**Comment by themazim** [comment]
@denisdulici back for good?

**Comment by denisdulici** [comment]
This has been fixed in 2.0 version.

**Pull request closed without merging**
