### PR TITLE
Invoice/Bill: Categories

### PR DESCRIPTION
**Pull request by denisdulici**

### CODE REVIEW

**Comment by sebadamus** [comment]
Excellent Denis!... would love to test it!

So to test it must do a reinstall? delete the DB, redownload repo 1.2 dev, composer install, and install normall as new? right?
Would be a mess to try to update database tables from old version to new one, I think.

Thanks

**Comment by denisdulici** [comment]
To test mus reinstall but the upgrade is ready there for the release.

Just fixed the price arrows.

Discount supports only percentage atm.

**Comment by EgyptianM** [comment]
When trying to add a new bill I get this error 
(2/2) QueryException
SQLSTATE[HY000]: 
```
General error: 1364 Field 'category_id' doesn't have a default value (SQL: insert into `aka_bills` (`vendor_id`, `currency_code`, `billed_at`, `due_at`, `bill_number`, `order_number`, `notes`, `company_id`, `vendor_name`, `vendor_email`, `vendor_tax_number`, `vendor_phone`, `vendor_address`, `currency_rate`, `bill_status_code`, `amount`, `updated_at`, `created_at`) values (4, EGP, 2018-04-23 00:00:00, 2018-04-23 00:00:00, 0000003, , , 1, حمدى عطية سيد, , , 01093284119, شيبسيات
01123840470, 1, draft, 0, 2018-04-25 08:32:44, 2018-04-25 08:32:44))
```

**Comment by denisdulici** [comment]
@EgyptianM Just fixed, thanks for reporting.

**Pull request merged**
