### PR TITLE
Correct Arabic words

### PR DESCRIPTION
**Pull request by mtawil**

### CODE REVIEW

**Comment by cuneytsenturk** [comment]
Mohammad AlTawil, can you plz send your translations to Crowdin https://crowdin.com/project/akaunting

**Comment by mtawil** [comment]
Thank you @cuneytsenturk.
A "Request to join" has been sent and waiting for approval.

**Comment by cuneytsenturk** [comment]
@mtawil I've confirm you.

**Comment by mtawil** [comment]
Thank you @cuneytsenturk.
I've been worked on for translating, correcting, reviewing and checking the Arabic language for more than 4 hours.
Please take your time to review and approve it.

**Comment by mtawil** [comment]
Hello, @cuneytsenturk.
Any updates regarding the translations?

**Pull request closed without merging**
