### PR TITLE
Add item & contact CRUD notification events

### PR DESCRIPTION
**Pull request by demirhanaydin**
When an item or contact is created, deleted, or updated, an event will be fired

### CODE REVIEW

**Comment by denisdulici** [comment]
Any reason for not using Eloquent events? https://laravel.com/docs/eloquent#events

**Comment by denisdulici** [comment]
You can use Observers to listen to Eloquent events: https://laravel.com/docs/eloquent#observers

**Comment by demirhanaydin** [comment]
Thanks a lot, I'll check it. Let's ignore this pr for now.

**Comment by denisdulici** [comment]
You're welcome 😉  

We generally fire events manually if there is more than Eloquent CRUD i.e. [invoice creation](https://github.com/akaunting/akaunting/blob/master/app/Jobs/Sale/CreateInvoice.php#L59).

**Comment by denisdulici** [comment]
[Here](https://akaunting.com/docs/developer-manual/hooking-models) I just created an example.

**Pull request closed without merging**
