### PR TITLE
pdf arabic , new document (postgresql issue), renaming 

### PR DESCRIPTION
**Pull request by ali3bdalla**
- [x] creating new document (using postgresql db)
- [x] render pdf with arabic support 
- [x] rename service providers to default laravel classes naming

### CODE REVIEW

**Comment by denisdulici** [comment]
Unfortunately, can't accept such a PR.

**Comment by mmegahed3046** [comment]
Is this working properly or what do 
I need to fix the pdf problem in Arabic
[bill-00001-1647815082.pdf](https://github.com/akaunting/akaunting/files/8312374/bill-00001-1647815082.pdf)

**Comment by Foad7117** [comment]
I am an Arab , Can I be considered a contributor if I fix this problem ?

**Comment by Foad7117** [comment]
I am an Arab , Can I be considered a contributor if I fix this problem :)

**Comment by Neustradamus** [comment]
@denisdulici: I do not understand your comment, can you explain?

**Pull request closed without merging**
