### PR TITLE
Fix invoice print layout and PDF

### PR DESCRIPTION
**Pull request by developerbmw**
I've changed the invoice view so that it is a standalone view, not including all the normal CSS / JS etc as that slows down the PDF massively. Check out how fast the PDF download is now...

Also I've completely re-done the layout using a combination of inline-block and tables which are supported by DOMPDF so now the PDF matches the print web page.

### CODE REVIEW

**Comment by developerbmw** [comment]
Fixes #171

**Comment by denisdulici** [comment]
Brett, we must keep the current structure in order to make the system extendible so instead of deleting, please apply the changes to layout + partial files and include them.

**Comment by developerbmw** [comment]
Thanks Denis, I have updated the commit

**Comment by denisdulici** [comment]
Perfect Brett :wink:

**Pull request merged**
