### PR TITLE
german Translation

### PR DESCRIPTION
**Pull request by cracker182**
Adds german translation for accounts.php

### CODE REVIEW

**Comment by denisdulici** [comment]
Thanks @cracker182 for your contribution. For translations, we use Crowdin as it's easier to manage so can you please send your translations there? https://crowdin.com/project/akaunting

**Comment by cracker182** [comment]
ok i will do

**Comment by cracker182** [comment]
Fully Translated on crowdin.

**Comment by denisdulici** [comment]
Awesome. Can you please now download the whole translation and submit it as a pull request? https://www.screencast.com/t/eKcjGPPG1S  I can do that for you but then GitHub won't list you on the contributors' page.

**Pull request closed without merging**
